export default {
  entity: 'frontend_3_3_1',
  primaryKey: 'location_id',
  createModal: 'sidebar',
  formComponent: () => import('@/views/app/FormComponent/LocationForm.vue'),
  options: {
    id: 'siderbar_location',
    shadow: true,
    rigth_position: true,
    no_header: true,
    custom_footer: false,
    backdrop: true,
    backdrop_variant: 'variant',
  },
  fields: [
    {
      key: 'locationtype_id',
      type: 'custom_list',
      list: 'locationtype',
      listLabel: 'locationtype_name',
      sortable: true,
      hideOnIndex: true,
      cols: 12,
    },

    { key: 'location_id', auto: true, size: 'sm' },
    { key: 'location_name', cols: 12 },
    {
      key: 'location_objectdescription', type: 'textarea', hideOnIndex: true, required: false, cols: 12,
    },
    // {
    //   key: 'location_total_area', type: 'number', hideOnIndex: true, required: false,
    // },
    // {
    //   key: 'location_start_date', type: 'date', hideOnIndex: true, required: false,
    // },
    { key: 'owner_name', cols: 12, type:'custom_list',list: 'patner' },
    // { key: 'manager_name', cols: 12 },
    // { key: 'locationtype_name', cols: 12 },
    {
      key: 'country_id',
      cols: 12,
      type: 'custom_list',
      label: 'Country',
      list: 'countrytype',
      listLabel: 'country_name',
      sortable: true,
      hideOnIndex: true
    },
    { key: 'city_Zip', cols: 4, label: 'Zip/code', hideOnIndex: true },
    { key: 'city_name', cols: 8, label: 'City' },
    { key: 'adress_name', cols: 8, label: 'Adress', hideOnIndex: true },
    { key: 'address_house_number', label: 'Nr.', cols: 4, hideOnIndex: true },
    // { key: 'area_count', cols: 12 },
    { key: 'country_name', cols: 4, label: 'Country', hideOnForm: true, hideOnCreate: true, hideOnUpdate: true },

    // {
    //   key: 'address_id',
    //   type: 'list',
    //   list: 'address',
    //   listLabel: 'address_street',
    //   hideOnIndex: true,
    //   withNew: true,
    //   alwaysNew: true,
    //   onlyForm:true,
    //   cols:12
    // },
  ],
  relations: [
    {
      title: 'Contracts',
      primaryKey: 'contract_id',
      entity: 'frontend_3_2_3_1',
      entityForm: 'contract_area_unit_usagetype_rel',
      entityView: 'contract',
      fields: [
        { key: 'contract_name', hideOnForm: true },
        { key: 'company_name', hideOnForm: true },
        { key: 'contract_begin_date', hideOnForm: true },
        { key: 'contract_end_date', hideOnForm: true },
      ],
    },
    // {
    //   title: 'Service Objects',
    //   entity: 'frontend_3_3_3_2',
    //   entityView: 'serviceobject',
    //   create: false,
    //   delete: false,
    //   update: false,
    //   primaryKey: 'serviceobject_id',
    //   fields: [
    //     {
    //       key: 'serviceobject_id',
    //       type: 'list',
    //       list: 'serviceobject',
    //       alwaysNew: true,
    //       onlyForm: true,
    //     },
    //     { key: 'serviceobject_id', hideOnForm: true },
    //     { key: 'serviceobject_name', hideOnForm: true },
    //     { key: 'serviceobject_external_name', hideOnForm: true },
    //     { key: 'serviceobjecttype_name', hideOnForm: true },
    //     { key: 'serviceobject_description', type: 'textarea', hideOnForm: true },
    //     { key: 'area_id', hideOnForm: true },
    //     { key: 'area_name' },
    //     { key: 'areatype_name' },
    //   ],
    // },
    // {
    //   title: 'Partner Companies',
    //   entity: 'frontend_3_3_3_3',
    //   entityForm: 'location_partnercompany_partnertype_rel',
    //   entityView: 'partnercompany',
    //   primaryKey: 'partnercompany_id',
    //   hideOnIndex:true,
    //   fields: [
    //     {
    //       key: 'partnercompany_id',
    //       type: 'list',
    //       list: 'partnercompany',
    //       listLabel: 'partnercompany_name',
    //       disableOnUpdate: true,
    //     },
    //     { key: 'partnercompany_name', hideOnForm: true },
    //     { key: 'partnergroup_name', hideOnForm: true },
    //     { key: 'partnertype_name', hideOnForm: true },
    //     {
    //       key: 'partnertype_id',
    //       hideOnIndex: true,
    //       type: 'list',
    //       composite: true,
    //       list: 'partnertype',
    //       listLabel: 'partnertype_name',
    //       disableOnUpdate: true,
    //     },
    //     { key: 'city_name', hideOnForm: true },
    //     { key: 'contactdetails_email', hideOnForm: true },
    //     { key: 'contactdetails_phone', hideOnForm: true },
    //     {
    //       key: 'location_partnercompany_partnertype_valid_from_date',
    //       type: 'date',
    //       composite: true,
    //       disableOnUpdate: true,
    //     },
    //     { key: 'location_partnercompany_partnertype_valid_to_date', type: 'date' },
    //   ],
    // },
  ],
  note: 'frontend_0_8_5',
}
